version: "3.7"

services:
  app:
    build: .
    networks:
      - categories-api-network
    container_name: app_categories_api
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
      - 443:${APPLICATION_PORT}
    depends_on:
      - database
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules

  database:
    image: postgres:13
    container_name: database_categories
    restart: always
    networks:
      - categories-api-network
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${NAME_DB}
    volumes:
      - pgdata:/data/postgres
networks:
  categories-api-network:
    driver: bridge

volumes:
  node_modules:
  pgdata:
    driver: local
